<form action="<?php echo $action; ?>" method="post">
	<fieldset>
		<div>
			<label for="title">Title</label>
			<input type="text" id="title" name="title" value="<?php if (isset($page['title'])) echo $page['title']; ?>" />
		</div>
		<div>
			<label for="content">Content</label>
			<textarea id="content" name="content" cols="60" rows="6"><?php if (isset($page['content'])) echo $page['content']; ?></textarea>
		</div>
		<div>
			<label for="publish">
				<input type="checkbox" id="publish" name="publish" <?php if (isset($page['publish']) && !empty($page['publish'])) echo 'checked'; ?> />Publish
			</label>
		</div>
		<div>
			<button type="submit">Save</button>
		</div>
	</fieldset>
</form>
