<?php if ($pages && !empty($pages)) :?>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Title</th>
				<th>State</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($pages as $page) : ?>
			<tr>
				<td><?php echo $page['id']; ?></td>
				<td><?php echo $page['title']; ?></td>
				<td><?php echo (!empty($page['publish']) ? 'published' : 'draft'); ?></td>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>
