<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php isset($title) ? $title : 'Blog'; ?></title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
</head>
<body>

<section class="container">
    <?php echo $body; ?>
</section>

<script type="text/javascript" src="/js/jquery-2.1.3.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
</body>
</html>
